pipeline:
  name: Build azure-repo
  identifier: Build_laxingTon_azure_repo_1709269742710
  projectIdentifier: harnessazuredeploy
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Welcome
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: Run
                  name: terraform_init
                  identifier: terraform_init
                  spec:
                    shell: Sh
                    command: terraform init
              - step:
                  type: Run
                  name: az_login
                  identifier: az_login
                  spec:
                    shell: Sh
                    command: az login
              - step:
                  type: Run
                  name: terrafom_plan
                  identifier: terrafom_plan
                  spec:
                    shell: Sh
                    command: terraform plan -var="resource_group_name=lax-harness-epp"
              - step:
                  type: Run
                  name: terraform_apply
                  identifier: terraform_apply
                  spec:
                    shell: Sh
                    command: terraform apply -var="resource_group_name=lax-harness-epp" -auto-approve
              - step:
                  type: Run
                  name: terraform_destroy
                  identifier: terraform_destroy
                  spec:
                    shell: Sh
                    command: terraform destroy -var="resource_group_name=lax-harness-epp" -auto-approve
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: laxingTon/azure-repo
        build: <+input>
